[package]
name = "emupico"
version = "0.0.1"
edition = "2024"

[dependencies]
camino = "1.2.2"
clap = { version = "4.5.57", features = ["derive"] }
mlua = { version = "0.11.6", features = ["lua52"] }
sdl2 = "0.38.0"
